server:
  port: 9201
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  application:
    name: exam-auth
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.181.101:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 114.116.114.181
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: exam_cloud_redis
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

wechat:
  weapp:
    appid: wxa3b4bed0624ba77c
    secret: 7fb75244d267cfa262cf12624716d3a5

logstash:
  host: 192.168.181.101
logging:
  level:
    root: info